#include <stdio.h>
#include <string.h>
#include <math.h>

#include "comm.h"
#include "db.h"
#include "events.h"
#include "interp.h"
#include "mm.h"
#include "new_combat_def.h"
#include "prototypes.h"
#include "spells.h"
#include "structs.h"
#include "utils.h"
#include "arena.h"
#include "arenadef.h"
#include "justice.h"
#include "weather.h"
#include "sound.h"
#include "objmisc.h"
#include "tradeskill.h"


struct forge_item forge_item_list[MAX_FORGE_ITEMS] = {
   //THIS FIRST IS UNSUSED
   {0, "armor mithril", "an mithril platemail forged by $s lies here" ,
       "%s mithril platemail",
       {LARGE_MITHRIL_ORE, 0,0,0,0},
       APPLY_DAMROLL, 0,0,
       APPLY_HITROLL, 0,3,
       1,100,
       ALLOW,
       CLASS_WARRIOR |CLASS_MERCENARY,
       ITEM_WEAR_BODY,
       0,0,0,0,
   },
{1, "crude iron plate leggings",
 "&+Lsome &+bcrude &+ciron &+Lplate leggings forged by &+W%s &+Llies here" ,
 "&+Lsome &+bcrude &+ciron &+Lplate leggings&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
  {2, "crude iron plate sleeves",
 "&+Lsome &+bcrude &+ciron &+Lplate sleeves forged by &+W%s &+Llies here" ,
 "&+Lsome &+bcrude &+ciron &+Lplate sleeves&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 0,1,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
  {3, "crude iron plate battle helm",
 "&+Lsome &+bcrude &+ciron &+Lplate b&+wa&+Wtt&+wl&+Le helm forged by &+W%s &+Llies here" ,
 "&+Lsome &+bcrude &+ciron &+Lplate b&+wa&+Wtt&+wl&+Lehelm&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
  {4, "crude iron plate gauntlets",
 "&+Lsome &+bcrude &+ciron &+Lplate gauntlets&+L lie here" ,
 "&+Lsome &+bcrude &+ciron &+Lplate gauntlets&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
     CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
 {5, "crude iron plate platemail",
 "&+Lsome &+bcrude &+ciron &+Lplatemail&n forged by &+W%s &+Llies here" ,
 "&+Lsome &+bcrude &+ciron &+Lplatemail &n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,LARGE_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
  {6, "crude copper mesh leggings",
 "&+ya pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y leggings sit here&n" ,
 "&+ya pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y leggings&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 5,10,
      1,100,
      ALLOW,
     CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
  {7, "crude copper mesh sleeves",
 "&+ya pair of cr&+Yud&+ye &+ycopper&n &+ym&+Ye&+ys&+Yh&+y sleeves&n &+Llies here" ,
 "&+ya pair of cr&+Yud&+ye &+ycopper&n &+ym&+Ye&+ys&+Yh&+y sleeves&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
    CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
  {8, "crude bronze mesh coif",
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y coif&n &+Llies here" ,
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y coif&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
     CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
  {9, "crude bronze mesh gauntlets",
 "&+ya pair of cr&+Yud&+ye &+ycopper&n &+ym&+Ye&+ys&+Yh&+y gauntlets&n &+Llies here" ,
 "&+ya pair of cr&+Yud&+ye &+ycopper&+ym&+Ye&+ys&+Yh&+y gauntlets&n",
      {MEDIUM_COPPER_ORE, MEDIUM_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
     CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
  {10, "crude copper mesh shirt",
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y shirt&n &+Llies here" ,
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y shirt&n",
      {LARGE_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
    CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{11, "coarse iron mantle",
"&+LA&n&+w coarse&n&+c iron&+L mantle lies here." ,
"&+La &n&+wcoarse&n&+c iron&+L mantle&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,
SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_BERSERKER,
      ITEM_WEAR_ABOUT,
	0,0,0,0,
  },
{12, "coarse iron sabatons",
"&+LSome&n &+wcoarse&n&+c iron&+L sabatons lay here." ,
"&+Lsome &n&+wcoarse&n&+c iron&+L sabtons",
      {SMALL_IRON_ORE,SMALL_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_THIEF|CLASS_ASSASSIN|CLASS_ALCHEMIST,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{13, "sturdy iron gauntlets",
"&+LA pair of &n&+Csturdy&n&+c iron&n&+L gauntlets collect dust here.",
"&+La pair of &n&+Csturdy&n&+c iron&+L gauntlets",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{14, "sturdy iron great helm",
  "&+LA &+Csturdy&n&+c iron&+L great helm collects dust here.",
  "&+La &+Csturdy &n&+ciron&+L great helm",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE, SMALL_IRON_ORE, SMALL_IRON_ORE,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      20,100,
      ALLOW,
     CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_BERSERKER|CLASS_RANGER,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{15 ,"magnificent iron breastplate",
"&+LA &+Wmagnificent&n&+c iron&+L breastplate forged by &+W%s&+L lies here.",
"&+La &+Wmagnificent&n&+c iron&+L breastplate forged by &+W%s",
      {LARGE_IRON_ORE, LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, 0},
      APPLY_DAMROLL, 1,2,
      APPLY_SAVING_SPELL, -1, -3,
      30,60,
      ALLOW,
      CLASS_WARRIOR|CLASS_PALADIN|CLASS_ANTIPALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{16 ,"sturdy iron visor",
"&+La &+Csturdy&n&+c iron &+Lvisor has been left here.",
"&+La &+Csturdy&n&+c iron &+Lvisor",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,SMALL_IRON_ORE, SMALL_IRON_ORE, 0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,2,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EYES,
	0,0,0,0,
  },
{17 ,"magnificent iron greaves",
"&+LA set of &+Wmagnificent&n&+c iron&+L greaves forged by &+W%s&+L has been left here.",
"&+La set of &+Wmagnificent&n&+c iron&+L greaves forged by &+W%s",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0},
      APPLY_HITROLL, 2,2,
      APPLY_SAVING_SPELL, -1, -2,
      30,60,
     ANTI,CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{18 ,"magnificent iron vambraces",
"&+La pair of &+Wmagnificent&n&+c iron&+L vambraces forged by &+W %s &+Lhave been left here.",
"&+LA pair of &+Wmagnificent&n&+c iron&+L vambraces forged by &+W %s",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,1,
      30,60,
      ANTI,
CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
     ITEM_WEAR_ARMS,
	0,0,0,0,
  },
{19 ,"magnificent iron sabatons",
"&+La pair of &+Wmagnificent&n&+c iron &+Lsabatons forged by&+W %s &+Lhave been left here.",
"&+La pair of &+Wmagnificent&n&+c iron&+L sabatons forged by&+W %s",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,LARGE_IRON_ORE,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_DAMROLL, 1,1,
      30,60,
      ANTI,
     CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
  ITEM_WEAR_FEET,
	0,0,0,0,
  },
{20 ,"magnificent iron visor",
"&+LA &+Wmagnificent&n&+c iron &+Lvisor forged by &+W%s&+L has been dropped here.",
"&+La &+Wmagnificent&n&+c iron&+L visor forged by &+W%s",
     {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE,0,0},
     APPLY_HITROLL, 1,2,
     APPLY_SAVING_FEAR, -2, -2,
     30,60,
     ANTI,
CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
ITEM_WEAR_EYES,
	0,0,0,0,
  },
{21 ,"sturdy iron tail ring",
"&+LA &+Csturdy&n&+c iron&+L tail ring has been dropped here.",
"&+La &+Csturdy&n&+c iron&+L tail ring",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_HIT, 2,6,
      APPLY_NONE, 0,0,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_TAIL,
	0,0,0,0,
  },
{22 ,"sturdy iron knuckles",
"&+LA pair of &+Csturdy&n&+c iron&+L knuckles has been dropped here.",
"&+La pair of &+Csturdy&n&+c iron&+L knuckles",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_HITROLL, 1,3,
      APPLY_NONE, 0,0,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },

{23, "rustic copper gauntlets",
 "&+Lsome &+brustic &+ycopper &+Lgauntlets&n forged by &+W%s &+Llies here" ,
 "&+Lsome &+brustic &+ycopper &+Lgauntlets&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_STR, 3,5,
      APPLY_CON, 3,5,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{24, "inferior iron leggings",
 "some &+rinferior&n &+ciron&n leggings forged by &+W%s &+Llies here" ,
 "some &+rinferior&n &+ciron&n leggings&n",
      {SMALL_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_MOVE, 6,10,
      APPLY_SAVING_PARA, -1,-2,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{25, "undeveloped mithril bracer",
 "an &+Mundeveloped&n &+mmithril&n bracer forged by &+W%s &+Llies here" ,
 "an &+Mundeveloped&n &+mmithril&n bracer&n",
      {SMALL_MITHRIL_ORE, 0,0,0,0},
      APPLY_STR, 3,5,
      APPLY_DEX, 3,5,
      1,100,
      ALLOW,
CLASS_THIEF|CLASS_MERCENARY|CLASS_BARD|CLASS_ASSASSIN,
      ITEM_WEAR_WRIST,
     0,0,0,0,
  },
{26, "simple copper chest plate",
 "a &+bsimple&n &+ycopper&n chest plate forged by &+W%s &+Llies here" ,
 "a &+bsimple&n &+ycopper&n chest plate&n",
      {SMALL_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HIT, 2,3,
      APPLY_DEX, 2,4,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{27, "rare gold earring",
 "a &+Brare&n &+Ygold&n earring forged by &+W%s &+Llies here" ,
 "a &+Brare&n &+Ygold&n earring&n",
      {MEDIUM_GOLD_ORE, MEDIUM_GOLD_ORE,0,0,0},
      APPLY_HIT, 6,9,
      APPLY_SAVING_PARA, -1,-3,
      1,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{28, "elegant silver necklace",
 "an &+Gel&+gega&+Gnt&n &+Csilver&n ne&+Cckl&nace forged by &+W%s &+Llies here" ,
 "an &+Gel&+gega&+Gnt&n &+Csilver&n ne&+Cckl&nace",
      {MEDIUM_SILVER_ORE, MEDIUM_SILVER_ORE,0,0,0},
      APPLY_CHA, 4,7,
      APPLY_CON, 6,8,
      10,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{29, "splendid gold boots",
 "a pair of &+Rspl&+ren&+Rdid&n &+Ygold&n b&+Yoo&nts forged by &+W%s &+Llies here",
 "a pair of &+Rspl&+ren&+Rdid&n &+Ygold&n b&+Yoo&nts",
      {SMALL_GOLD_ORE, SMALL_GOLD_ORE,0,0,0},
      APPLY_MOVE, 25,30,
      APPLY_CON, 6,8,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{30, "inferior copper boots",
 "a pair of &+Linferior&n &+ycopper&n b&+yoo&nts forged by &+W%s &+Llies here" ,
 "a pair of &+Linferior&n &+ycopper&n b&+yoo&nts&n",
      {SMALL_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_DEX, 1,3,
      APPLY_CON, 1,4,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{31, "refined platinum gauntlets",
 "a pair of &+mre&+Mfi&+mned &+Cplatinum &nga&+Cun&ntlets forged by &+W%s &+Llies here" ,
 "a pair of &+mre&+Mfi&+mned &+Cplatinum &nga&+Cun&ntlets",
    {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_AGI, 3,6,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{32, "refined platinum bracer",
 "a pair of &+mrefined &+Cplatinum&n br&+Cac&ners forged by &+W%s &+Llies here" ,
 "a pair of &+mrefined &+Cplatinum&n br&+Cac&ners&n",
     {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_AGI, 3,6,
      1,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{33, "refined platinum crown",
 "a  &+mrefined &+Cplatinum&n cr&+Cow&nn forged by &+W%s &+Llies here" ,
 "a  &+mrefined &+Cplatinum&n cr&+Cow&nn&n",
     {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_INT_MAX, 2,4,
      APPLY_AGI, 5,7,
      40,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{34, "refined platinum chainmail",
 "a  &+mrefined &+Cplatinum&n cha&+Cinm&nail forged by &+W%s &+Llies here" ,
 "a  &+mrefined &+Cplatinum&n cha&+Cinm&nail&n",
{MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_INT_MAX, 2,4,
      APPLY_AGI_MAX, 2,5,
      30,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{35, "elegant silver arm guards",
 "some &+Gelegant&n &+Csilver&n &+Lar&+wm guar&+Lds&n forged by &+W%s &+Llies here" ,
 "some &+Gelegant&n &+Csilver&n &+Lar&+wm guar&+Lds&n&n",
      {MEDIUM_SILVER_ORE, MEDIUM_SILVER_ORE,0,0,0},
      APPLY_DEX, 7,9,
      APPLY_CON, 6,9,
      10,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
{36, "dainty silver cord",
 "a &+gdainty&n &+Csilver&n &+bc&+Bor&+bd forged by &+W%s &+Llies here" ,
 "a &+gdainty&n &+Csilver&n &+bc&+Bor&+bd&n",
      {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
      APPLY_SAVING_SPELL, -2,-5,
      APPLY_WIS, 5,8,
      10,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,0,0,
  },
{37, "mediocre iron knee guards",
 "some &+Rmediocre&n &+ciron&n &+Gkne&+ge guar&+Gds&n forged by &+W%s &+Llies here" ,
 "some &+Rmediocre&n &+ciron&n &+Gkne&+ge guar&+Gds&n&n",
      {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
      APPLY_SAVING_PARA, -1,-3,
      APPLY_LUCK, 7,9,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{38, "mediocre mithril mask",
 "a &+Rmed&+rio&+Rcre&n &+mmithril&n &+mm&+Las&+mk&n forged by &+W%s &+Llies here" ,
 "a &+Rmed&+rio&+Rcre&n &+mmithril&n &+mm&+Las&+mk&n",
      {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_SAVING_FEAR, -1,-3,
      APPLY_LUCK_MAX, 2,5,
      1,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FACE,
	0,AFF2_FIRESHIELD,0,0,
  },
{39, "mediocre mithril platemail",
 "a &+Rmediocre&n &+mmithril&n pla&+mtem&nail forged by &+W%s &+Llies here" ,
 "a &+Rmediocre&n &+mmithril&n pla&+mtem&nail",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_SAVING_PARA, -3,-4,
      APPLY_LUCK_MAX, 2,5,
      20,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_BODY,
	0,AFF2_FIRESHIELD,0,0,
  },
{40, "mediocre mithril  bracer",
 "a &+Rmed&+rio&+Rcre&n &+mmithril&n &+Lbr&+wac&+Ler&n forged by &+W%s &+Llies here" ,
 "a &+Rmed&+rio&+Rcre&n &+mmithril&n &+Lbr&+wac&+Ler&n&n",
   {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HIT, 7,10,
      APPLY_DEX, 5,8,
      20,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,AFF2_ULTRAVISION,0,0,
  },
{41, "superior gold bracelet",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n br&+Yace&nlet forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n br&+Yace&nlet",
     {MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0},
      APPLY_CON, 4,6,
      APPLY_WIS_MAX, 1,2,
      40,50,
      ALLOW,
     CLASS_CLERIC|CLASS_SHAMAN|CLASS_DRUID,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{42, "superior gold eyelets",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n eyelets forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n eyelets&n",
{SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0},
      APPLY_CON, 2,6,
      APPLY_SAVING_BREATH, -2,-3,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EYES,
	0,0,0,0,
  },
{43, "superior gold horns",
 "a pair of &+Bsup&+ber&+Bior&n &+Ygold&n horns forged by &+W%s &+Llies here" ,
 "a pair of &+Bsup&+ber&+Bior&n &+Ygold&n horns&n",
{SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,0,0},
      APPLY_INT, 2,6,
      APPLY_AGI, 4,6,
      30,60,
      ALLOW,
    CLASS_ETHERMANCER|CLASS_SORCERER|CLASS_CONJURER|CLASS_BARD,
      ITEM_WEAR_HORN,
	AFF_PROT_FIRE,0,0,0,
  },
{44, "superior gold bracer",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n bracer forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n bracer&n",
     {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,0,0},
      APPLY_INT, 4,6,
      APPLY_FIRE_PROT, 1,1,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{45, "superior gold helmet",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n helmet forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n helmet&n",
     {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
      APPLY_CON, 5,8,
      APPLY_HIT, 8,10,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{46, "superior gold earring",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n earring forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n earring&n",

{SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
      APPLY_STR, 4,6,
      APPLY_HIT, 12,15,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{47, "superior gold mask",
 "a &+Bsup&+ber&+Bior&n &+Ygold&n mask forged by &+W%s &+Llies here" ,
 "a &+Bsup&+ber&+Bior&n &+Ygold&n mask&n",
{SMALL_GOLD_ORE,0,0,0,0},
      APPLY_DEX, 7,8,
      APPLY_HITROLL, 4,5,
      10,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{48, "cheap mithril gauntlets",
 "a &+Bcheap&n &+mmithril&n gauntlets forged by &+W%s &+Llies here" ,
 "a &+Bcheap&n &+mmithril&n gauntlets&n",
{MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_LUCK, 7,8,
      APPLY_AGI, 6,8,
      10,90,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HANDS,
	AFF_WATERBREATH,0,0,0,
  },
{49, "excellent mithril crown",
 "a &+Bexcellent&n &+mmithril&n crown forged by &+W%s &+Llies here" ,
 "a &+Bexcellent&n &+mmithril&n crown&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_CON_MAX, 2,3,
      APPLY_SAVING_BREATH, -2,-3,
      20,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	AFF_AWARE,0,0,0,
  },
{50, "excellent mithril belt",
 "an &+Bexcellent&n &+mmithril&n belt forged by &+W%s &+Llies here" ,
 "an &+Bexcellent&n &+mmithril&n belt&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_AGI, 5,7,
      APPLY_HITROLL, 1,3,
      30,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,AFF3_COLDSHIELD,0,
  },
{51, "amazing mithril boots",
 "some &+Gamazing&n &+mmithril&n boots forged by &+W%s &+Llies here" ,
 "some &+Gamazing&n &+mmithril&n boots&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HIT, 10,15,
      30,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,AFF3_COLDSHIELD,0,
  },
{52, "godly mithril boots",
 "some &+mgodly&n &+mmithril&n boots forged by &+W%s &+Llies here" ,
 "some &+mgodly&n &+mmithril&n boots&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,5,
      APPLY_INT, 4,5,
      60,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{53, "holy mithril chainmail",
 "some &+Yholy&n &+mmithril&n chainmail forged by &+W%s &+Llies here" ,
 "some &+Yholy&n &+mmithril&n chainmail&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 3,4,
      APPLY_AGI_MAX, 2,3,
      30,60,
      ALLOW,
     CLASS_CLERIC|CLASS_SHAMAN|CLASS_DRUID|CLASS_ETHERMANCER,
      ITEM_WEAR_BODY,
	AFF_FLY,0,0,0,
  },
{54, "holy mithril gauntlets",
 "a pair of &+Yholy&n &+mmithril&n gauntlets forged by &+W%s &+Llies here" ,
 "a pair of &+Yholy&n &+mmithril&n gauntlets&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
     CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_HANDS,
	AFF_FLY,0,0,0,
  },
{55, "holy mithril greaves",
 "a pair of &+Yholy&n &+mmithril&n greaves forged by &+W%s &+Llies here" ,
 "a pair of &+Yholy&n &+mmithril&n greaves&n",
{MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 2,3,
      APPLY_DAMROLL, 1,2,
      30,30,
      ALLOW,
     CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	AFF_WATERBREATH,0,0,0,
  },
{56, "holy mithril leggings",
 "a pair of &+Yholy&n &+mmithril&n leggings forged by &+W%s &+Llies here" ,
 "a pair of &+Yholy&n &+mmithril&n leggings&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 1,3,
      APPLY_SAVING_SPELL, -1,-2,
      30,30,
      ALLOW,
     CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{57, "unholy mithril gauntlets",
 "a pair of &+runholy&n &+mmithril&n gauntlets forged by &+W%s &+Llies here" ,
 "a pair of &+runholy&n &+mmithril&n gauntlets&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
     CLASS_BERSERKER|CLASS_ANTIPALADIN|CLASS_CLERIC,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{58, "unholy mithril platemail",
 "an &+runholy&n &+mmithril&n &+Lplat&+wema&+Lil&n forged by &+W%s &+Llies here" ,
 "an &+runholy&n &+mmithril&n &+Lplat&+wema&+Lil&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
     CLASS_ANTIPALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{59, "unholy mithril leggings",
 "a pair of &+runholy&n &+mmithril&n leggings forged by &+W%s &+Llies here" ,
 "a pair of &+runholy&n &+mmithril&n leggings&n",
{MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 1,3,
      APPLY_SAVING_SPELL, -2,-3,
      30,30,
      ALLOW,
     CLASS_ANTIPALADIN|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	AFF_FLY,0,0,0,
  },
{60, "crafty copper crown",
 "a &+Mcrafty&n &+ycopper&n crown forged by &+W%s &+Llies here" ,
 "a &+Mcrafty&n &+ycopper&n crown&n",
{SMALL_COPPER_ORE,0,0,0,0},
      APPLY_LUCK, 3,5,
      APPLY_SAVING_FEAR, -2,-3,
      1,100,
      ALLOW,
     CLASS_ALCHEMIST,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{61, "crafty iron crown",
 "a &+Mcrafty&n &+ciron&n crown forged by &+W%s &+Llies here" ,
 "a &+Mcrafty&n &+ciron&n crown&n",
{SMALL_IRON_ORE,0,0,0,0},
      APPLY_LUCK, 5,6,
      APPLY_LUCK_MAX, 3,4,
      20,80,
      ALLOW,
     CLASS_ALCHEMIST,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{62, "gothic iron circlet",
 "a &+Lgo&+wth&+Lic &+ciron&n &+Bci&+brcl&+Bet&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+ciron&n &+Bci&+brcl&+Bet&n",
{SMALL_IRON_ORE,MEDIUM_IRON_ORE,0,0,0},
      APPLY_CHA, 2,4,
      APPLY_SAVING_SPELL, -2,-3,
      30,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{63, "gothic iron gauntlets",
 "some &+Lgo&+wth&+Lic &+ciron&n &+Bgau&+bntl&+Bets&n forged by &+W%s &+Llies here" ,
 "some &+Lgo&+wth&+Lic &+ciron&n &+Bgau&+bntl&+Bets&n",
{SMALL_IRON_ORE,MEDIUM_IRON_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_SAVING_SPELL, -2,-3,
      30,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{64, "gothic iron boots",
 "some &+Lgo&+wth&+Lic &+ciron&n &+Bb&+boots&n forged by &+W%s &+Llies here" ,
 "some &+Lgo&+wth&+Lic &+ciron&n &+Bb&+boots&n",
{SMALL_IRON_ORE,MEDIUM_IRON_ORE,MEDIUM_IRON_ORE,0,0},
      APPLY_HIT, 5,7,
      APPLY_MOVE, 8,10,
      40,70,
      ANTI,
     CLASS_NONE,
     ITEM_WEAR_FEET,
	0,0,0,0,
  },
{65, "gothic iron veil",
 "a &+Lgo&+wth&+Lic &+ciron&n &+Bv&+beil&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+ciron&n &+Bv&+beil&n",
{SMALL_IRON_ORE,0,0,0,0},
      APPLY_HIT, 5,8,
      APPLY_SAVING_SPELL, -1,-2,
      1,90,
      ANTI,
     CLASS_NONE,
     ITEM_WEAR_FACE,
	0,0,0,0,
  },
{66, "gothic copper veil",
 "a &+Lgo&+wth&+Lic &+ycopper&n &+Bv&+beil&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+ycopper&n &+Bv&+beil&n",
{SMALL_COPPER_ORE,LARGE_COPPER_ORE,0,0,0},
      APPLY_HIT, 8,10,
      APPLY_SAVING_SPELL, -1,-3,
      1,80,
      ANTI,
     CLASS_NONE,
     ITEM_WEAR_FACE,
	0,0,0,0,
  },
{67, "gothic copper boots",
 "some &+Lgo&+wth&+Lic &+ycopper&n &+Bb&+boots&n forged by &+W%s &+Llies here" ,
 "some &+Lgo&+wth&+Lic &+ycopper&n &+Bb&+boots&n",
{SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_HIT, 7,10,
      APPLY_MOVE, 12,15,
      40,60,
      ANTI,
     CLASS_NONE,
     ITEM_WEAR_FEET,
	0,0,0,0,
  },
{68, "gothic copper gauntlets",
 "some &+Lgo&+wth&+Lic &+ycopper&n &+Bgau&+bntl&+Bets&n forged by &+W%s &+Llies here" ,
 "some &+Lgo&+wth&+Lic &+ycopper&n &+Bgau&+bntl&+Bets&n",
{SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 2,3,
      APPLY_SAVING_SPELL, -2,-3,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{69, "gothic copper circlet",
 "a &+Lgo&+wth&+Lic &+ycopper&n &+Bci&+brcl&+Bet&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+ycopper&n &+Bci&+brcl&+Bet&n",
{SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0,0},
      APPLY_CHA, 6,8,
      APPLY_SAVING_SPELL, -2,-3,
      30,60,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{70, "basic copper robe",
 "a &+Lba&+ws&+Lic&n &+ycopper&n &+Lrobe&n forged by &+W%s &+Llies here" ,
 "a &+Lba&+ws&+Lic&n &+ycopper&n &+Lrobe&n",
{SMALL_COPPER_ORE,0,0,0,0},
      APPLY_DEX, 3,4,
      APPLY_DAMROLL, 1,2,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{71, "embossed copper crown",
 "an &+Lembo&+css&+Led&n &+ycopper &+Lcrown&n forged by &+W%s &+Llies here" ,
 "an &+Lembo&+css&+Led&n &+ycopper &+Lcrown&n",
{SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_SPELL, -2,-3,
      APPLY_HIT,8,14,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{72, "embossed copper bracelet",
 "an &+Lembo&+css&+Led&n &+ycopper &+Bb&+bracelet&n forged by &+W%s &+Llies here" ,
 "an &+Lembo&+css&+Led&n &+ycopper &+Bb&+bracelet&n",
{SMALL_COPPER_ORE,SMALL_COPPER_ORE,0,0,0},
      APPLY_CON,3,5,
      APPLY_STR,3,5,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{73, "embossed copper bracer",
 "an &+Lembo&+css&+Led&n &+ycopper &+Lbracer&n forged by &+W%s &+Llies here" ,
 "an &+Lembo&+css&+Led&n &+ycopper &+Lbracer&n",
{SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_SPELL, -2,-3,
      APPLY_HIT,6,8,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{74, "embossed copper boots",
 "a pair of &+Lembo&+css&+Led&n &+ycopper &+Bb&+boots&n forged by &+W%s &+Llies here" ,
 "a pair of &+Lembo&+css&+Led&n &+ycopper &+Bb&+boots&n",
{SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_PARA, -2,-3,
      APPLY_MOVE,12,15,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{75, "embossed copper necklace",
 "an &+Lembo&+css&+Led&n &+ycopper &+Bn&+becklace&n forged by &+W%s &+Llies here" ,
 "an &+Lembo&+css&+Led&n &+ycopper &+Bn&+becklace&n",
{SMALL_COPPER_ORE,0,0,0,0},
      APPLY_DEX, 4,5,
      APPLY_CHA,7,8,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{76, "gothic silver cord",
 "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+bor&+Bd&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+bor&+Bd&n",
{SMALL_SILVER_ORE,0,0,0,0},
      APPLY_CON, 4,5,
      APPLY_DAMROLL,1,2,
      1,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{77, "gothic silver necklace",
 "a &+Lgo&+wth&+Lic &+wsilver &+Bn&+becklace&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+wsilver &+Bn&+becklace&n",
{LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0,0},
      APPLY_CON, 8,9,
      APPLY_AGI,8,9,
      20,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{78, "gothic silver bracer",
 "a &+Lgo&+wth&+Lic &+wsilver &+Bb&+bracer&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+wsilver &+Bb&+bracer&n",
{LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
      APPLY_HITROLL, 1,3,
      APPLY_DAMROLL,2,2,
      40,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{79, "gothic silver mask",
 "a &+Lgo&+wth&+Lic &+wsilver &+Bm&+bask&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+wsilver &+Bm&+bask&n",
{LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
      APPLY_CON, 5,7,
      APPLY_SAVING_BREATH,-2,-3,
      40,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{80, "gothic silver circlet",
 "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+birclet&n forged by &+W%s &+Llies here" ,
 "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+birclet&n",
{LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0},
      APPLY_HIT, 12,15,
      APPLY_INT_MAX,2,3,
      60,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{81, "chaotic mithril leg plates",
 "some &+rcha&+Ro&+rtic&n &+mmithril &+Gleg plates&n forged by &+W%s &+Llie here" ,
 "some &+rcha&+Ro&+rtic&n &+mmithril &+Gleg plates&n",
{LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DEX_MAX,2,3,
      40,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{82, "chaotic mithril chainmail",
 "a &+rcha&+Ro&+rtic&n &+mmithril &+Lcha&+rinm&+Lail&n forged by &+W%s &+Llies here" ,
 "a &+rcha&+Ro&+rtic&n &+mmithril &+Lcha&+rinm&+Lail&n",
{LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0},
      APPLY_HIT, 23,25,
      APPLY_WIS_MAX,2,4,
      70,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{83, "chaotic platinum band",
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lband&n forged by &+W%s &+Llies here" ,
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lband&n",
{SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_HIT, 13,15,
      APPLY_AGI_MAX,3,4,
      40,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FINGER,
	0,0,0,0,
  },
{84, "chaotic platinum visor",
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lvisor&n forged by &+W%s &+Llies here" ,
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lvisor&n",
{SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_CHA, 6,8,
      APPLY_AGI_MAX,2,3,
      40,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EYES,
	AFF_WATERBREATH,0,0,0,
  },
{85, "chaotic platinum leggings",
 "some &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lleggings&n forged by &+W%s &+Llies here" ,
 "some &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lleggings&n",
{SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_AGI, 11,12,
      APPLY_STR_MAX,1,2,
      40,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_LEGS,
	AFF_WATERBREATH,0,0,0,
  },
{86, "chaotic platinum sash",
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lsash&n forged by &+W%s &+Llies here" ,
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lsash&n",
{SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_DEX, 10,12,
      APPLY_STR,1,2,
      40,70,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WAIST,
	AFF_WATERBREATH,0,0,0,
  },
{87, "chaotic platinum shield",
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lshield&n forged by &+W%s &+Llies here" ,
 "a &+rcha&+Ro&+rtic&n &+Wplatinum&n &+Lshield&n",
{SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_STR_MAX,1,3,
      40,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_SHIELD,
	AFF_WATERBREATH,0,0,0,
  },
{88, "exquisite silver earring",
 "an &+Cex&+cquisi&+Cte&n &+wsilver&n &+Lea&+wrr&+Ling&n with a &+ygo&+Yld&+yen nail&n forged by &+W%s &+Llies here" ,
 "an &+Cex&+cquisi&+Cte&n &+wsilver&n &+Lea&+wrr&+Ling&n with a &+ygo&+Yld&+yen nail&n",
{MEDIUM_SILVER_ORE,SMALL_GOLD_ORE,0,0,0},
      APPLY_CHA, 7,8,
      APPLY_SAVING_FEAR,-1,-2,
      40,50,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{89, "exquisite golden earring",
 "an &+Cex&+cquisi&+Cte&n &+Ygolden&n &+Lea&+wrr&+Ling&n with a &+Wplatinum&n &+ynail&n forged by &+W%s &+Llies here" ,
 "an &+Cex&+cquisi&+Cte&n &+Ygolden&n &+Lea&+wrr&+Ling&n with a &+Wplatinum&n &+ynail&n",
{MEDIUM_GOLD_ORE,SMALL_PLATINUM_ORE,0,0,0},
      APPLY_CHA, 10,11,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
  {90, "simple golden earring",
 "A &+Rs&+rimpl&+Re&n &+Wplatinum&n &+Lea&+wrr&+Ling&n with a &+mmithril&n &+ynail&n forged by &+W%s &+Llies here." ,
 "a &+Rs&+rimpl&+Re&n &+Wplatinum&n &+Lea&+wrr&+Ling&n with a &+mmithril&n &+ynail&n",
{MEDIUM_GOLD_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_CHA_MAX, 2,3,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
      AFF_FARSEE,0,0,0,
  },
  {91, "exquisite golden earring",
 "an &+Cex&+cquisi&+Cte&n &+mmithril&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "an &+Cex&+cquisi&+Cte&n &+mmithril&n &+Lea&+wrr&+Ling&n",
      {MEDIUM_MITHRIL_ORE,0,0,0,0},
      APPLY_CHA_MAX, 3,4,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	AFF_FARSEE,0,0,0,
  },
  {92, "clover leaf copper earring",
 "a &+gcl&+Gov&+ger &+Gleaf&n &+ycopper&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "a &+gcl&+Gov&+ger &+Gleaf&n &+ycopper&n &+Lea&+wrr&+Ling&n",
      {SMALL_COPPER_ORE,0,0,0,0},
      APPLY_LUCK, 3,4,
      APPLY_SAVING_PARA,-1,-1,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
   {93, "clover leaf silver earring",
 "a &+gcl&+Gov&+ger &+Gleaf&n &+wsilver&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "a &+gcl&+Gov&+ger &+Gleaf&n &+wsilver&n &+Lea&+wrr&+Ling&n",
      {SMALL_SILVER_ORE,0,0,0,0},
      APPLY_LUCK, 4,5,
      APPLY_SAVING_PARA,-1,-1,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
  {94, "clover leaf golden earring",
 "a &+gcl&+Gov&+ger &+Gleaf&n &+Ygolden&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "a &+gcl&+Gov&+ger &+Gleaf&n &+Ygolden&n &+Lea&+wrr&+Ling&n",
      {SMALL_GOLD_ORE,0,0,0,0},
      APPLY_LUCK_MAX, 2,3,
      APPLY_SAVING_PARA,-2,-3,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
  {95, "clover leaf platinum earring",
 "a &+gcl&+Gov&+ger &+Gleaf&n &+Wplatinum&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "a &+gcl&+Gov&+ger &+Gleaf&n &+Wplatinum&n &+Lea&+wrr&+Ling&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0,0},
      APPLY_LUCK_MAX, 2,3,
      APPLY_HIT,8,10,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
   {96, "clover leaf mithril earring",
 "a &+gcl&+Gov&+ger &+Gleaf&n &+mmithril&n &+Lea&+wrr&+Ling&n forged by &+W%s &+Llies here" ,
 "a &+gcl&+Gov&+ger &+Gleaf&n &+mmithril&n &+Lea&+wrr&+Ling&n",
      {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_LUCK_MAX, 4,5,
      APPLY_HIT,13,15,
      60,80,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_EARRING,
	AFF_AWARE,0,0,0,
  },
   {97, "hammered iron leg plates",
 "some &+rha&+Rmm&+rered&n &+ciron&n &+yleg pl&+Late&+ys&n forged by &+W%s &+Llies here" ,
 "some &+rha&+Rmm&+rered&n &+ciron&n &+yleg pl&+Late&+ys&n",
      {SMALL_IRON_ORE,MEDIUM_IRON_ORE,MEDIUM_IRON_ORE,0,0},
      APPLY_CON, 4,5,
      APPLY_HIT,7,8,
      20,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
   {98, "irridescent square shield of mithril",
 "an &+Cirr&+wide&+Cs&+cc&+Cent&n &+bsquare &+Bsh&+bie&+Bld&n of &+mmithril&n forged by &+W%s &+Llies here" ,
 "an &+Cirr&+wide&+Cs&+cc&+Cent&n &+bsquare &+Bsh&+bie&+Bld&n of &+mmithril&n",
      {MEDIUM_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0,0},
      APPLY_CON_MAX, 2,3,
      APPLY_DEX_MAX,1,2,
      20,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_SHIELD,
	AFF_AWARE,0,0,0,
  },
    {99, "irridescent mask of hammered mithril",
 "an &+Cirr&+wide&+Cs&+cc&+Cent&n &+Bm&+bas&+Bk&n of &+rha&+Rmm&+Rered&n &+mmithril&n forged by &+W%s &+Llies here" ,
 "an &+Cirr&+wide&+Cs&+cc&+Cent&n &+Bm&+bas&+Bk&n of &+rha&+Rmm&+Rered&n &+mmithril&n",
      {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0},
      APPLY_WIS_MAX, 2,3,
      APPLY_DEX,4,6,
      20,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_FACE,
	AFF_FARSEE,0,0,0,
  },
   {100, "elaborate chain of platinum and silver",
 "an &+Bel&+babo&+Brate&n &+Cch&+cai&+Cn&n of &+Wplatinum&n and &+wsilver&n forged by &+W%s &+Llies here" ,
 "an &+Bel&+babo&+Brate&n &+Cch&+cai&+Cn&n of &+Wplatinum&n and &+wsilver&n",
      {MEDIUM_PLATINUM_ORE,MEDIUM_SILVER_ORE,0,0,0},
      APPLY_CHA, 6,8,
      APPLY_AGI,6,8,
      20,100,
      ANTI,
     CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,0,0,
  },
    {101, "hammered copper breastplate",
   "A &+Lha&+wmm&+Lered&n &+ycopper&n &+Wbre&+wastpl&+Wate&n forged by &+W%s &+Llies here." ,
   "a &+Lha&+wmm&+Lered&n &+ycopper&n &+Wbre&+wastpl&+Wate&n",
        {MEDIUM_COPPER_ORE,LARGE_COPPER_ORE,LARGE_COPPER_ORE,0,0},
        APPLY_CON, 5,6,
        APPLY_HIT,7,9,
        20,100,
        ANTI,
       CLASS_NONE,
        ITEM_WEAR_BODY,
  	0,0,0,0,
  },
  {102, "hammered silver breastplate",
     "A &+Lha&+wmm&+Lered&n &+wsilver&n &+Wbre&+wastpl&+Wate&n forged by &+W%s &+Llies here." ,
     "a &+Lha&+wmm&+Lered&n &+wsilver&n &+Wbre&+wastpl&+Wate&n",
          {MEDIUM_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
          APPLY_CON, 5,6,
          APPLY_HIT,13,15,
          20,100,
          ANTI,
         CLASS_NONE,
          ITEM_WEAR_BODY,
    	0,0,0,0,
  },
  {103, "exquisite chain of mithril with platinum and silver links",
       "An &+Cex&+cquisi&+Cte&n &+Wch&+Wai&+wn&n of &+mmithril&n with &+Wplatinum&n and &+wsilver&n &+Cl&+cin&+Cks&n forged by &+W%s &+Llies here." ,
       "an &+Cex&+cquisi&+Cte&n &+Wch&+Wai&+wn&n of &+mmithril&n with &+Wplatinum&n and &+wsilver&n &+Cl&+cin&+Cks&n",
            {MEDIUM_SILVER_ORE,LARGE_MITHRIL_ORE,MEDIUM_PLATINUM_ORE,0,0},
            APPLY_INT_MAX, 1,2,
            APPLY_HIT,13,15,
            60,60,
            ANTI,
           CLASS_NONE,
            ITEM_WEAR_WAIST,
      	0,0,0,0,
  },
  {104, "irridescent mithril leggings with copper details ",
         "A pair of &+Cirr&+wide&+Cs&+cc&+Cent&n &+mmithril&n &+Ll&+wegg&+Lings&n with &+ycopper&n &+Lde&+ytai&+Lls&n forged by &+W%s &+Llies here." ,
         "a pair of &+Cirr&+wide&+Cs&+cc&+Cent&n &+mmithril&n &+Ll&+wegg&+Lings&n with &+ycopper&n &+Lde&+ytai&+Lls&n",
              {MEDIUM_SILVER_ORE,LARGE_MITHRIL_ORE,MEDIUM_PLATINUM_ORE,0,0},
              APPLY_MOVE, 27,30,
              APPLY_DEX,3,4,
              20,90,
              ANTI,
             CLASS_NONE,
              ITEM_WEAR_LEGS,
        	0,0,0,0,
  },
  {105, "irridescent mithril torque",
           "An &+Cirr&+wide&+Cs&+cc&+Cent&n &+mmithril&n &+Lto&+wrqu&+Le&n forged by &+W%s &+Llies here." ,
           "an &+Cirr&+wide&+Cs&+cc&+Cent&n &+mmithril&n &+Lto&+wrqu&+Le&n",
                {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
                APPLY_HIT, 2,3,
                APPLY_DEX,4,5,
                20,90,
                ANTI,
               CLASS_NONE,
                ITEM_WEAR_NECK,
          	0,AFF2_ULTRAVISION,0,0,
  },
  {106, "noisy set of linked thick platinum and electrum plaques ",
             "A &+Yno&+yis&+Yy&n set of &+Ll&+Wi&+Ln&+Wk&+Le&+Wd&n thick &+Wplatinum&n and &+Celectrum&n &+Wpl&+Caqu&+Wes&n forged by &+W%s &+Llies here." ,
             "a &+Yno&+yis&+Yy&n set of &+Ll&+Wi&+Ln&+Wk&+Le&+Wd&n thick &+Wplatinum&n and &+Celectrum&n &+Wpl&+Caqu&+Wes&n",
                  {MEDIUM_PLATINUM_ORE,SMALL_SILVER_ORE,LARGE_GOLD_ORE,0,0},
                  APPLY_CON_MAX, 4,5,
                  APPLY_DEX,-5,-6,
                  20,90,
                  ANTI,
                 CLASS_NONE,
                  ITEM_WEAR_BODY,
            	0,0,0,0,
},
{107, "glowing copper shoes",
             "A &+Rpair&n of small &+Ygl&+Wow&+Ying&n &+ycopper&n &+Bs&+bhoe&+Bs&n forged by &+W%s &+Llies here." ,
             "a &+Rpair&n of small &+Ygl&+Wow&+Ying&n &+ycopper&n &+Bs&+bhoe&+Bs&n",
                  {MEDIUM_COPPER_ORE,SMALL_COPPER_ORE,0,0,0},
                  APPLY_MOVE, 18,20,
                  APPLY_CON,3,5,
                  20,90,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_FEET,
            	0,0,0,0,
},
{108, "tiny platinum stud glowing with raw power",
             "&+wA tiny &+Wplatinum&n &+ystud&n &+Cglowing&n &+wwith raw&n &+Rp&+ro&+Rw&+re&+Rr&+w&n forged by &+W%s &+Llies here." ,
             "&+wa tiny &+Wplatinum&n &+ystud&n &+Cglowing&n &+wwith raw&n &+Rp&+ro&+Rw&+re&+Rr&+w&n",
                  {MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0,0},
                  APPLY_POW, 8,10,
                  APPLY_POW_MAX,2,4,
                  20,90,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_EARRING,
            	0,0,0,0,
},
{109, "evil looking iron war helm ",
             "An &+re&+Rv&+ri&+Rl&n looking &+ciron &+rwar helm &+wwith &+rnasty sp&+Lik&+res&+w forged by &+W%s &+Llies here." ,
             "an &+re&+Rv&+ri&+Rl&n looking &+ciron &+rwar helm &+wwith &+rnasty sp&+Lik&+res&+w",
                  {SMALL_IRON_ORE,MEDIUM_IRON_ORE,LARGE_IRON_ORE,0,0},
                  APPLY_STR, 4,5,
                  APPLY_SAVING_SPELL,-1,-2,
                  20,90,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_HEAD,
            	0,0,0,0,
},
{110, "beautiful pair of mithril eyeglasses",
             "A &+wb&+Ce&+wa&+Cut&+wi&+Cfu&+wl &+wpair of &+mmithril &+we&+Cy&+We&+wg&+Cl&+Wa&+ws&+Cs&+We&+ws forged by &+W%s &+Llies here." ,
             "a &+wb&+Ce&+wa&+Cut&+wi&+Cfu&+wl &+wpair of &+mmithril &+we&+Cy&+We&+wg&+Cl&+Wa&+ws&+Cs&+We&+ws",
                  {SMALL_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
                  APPLY_INT_MAX, 2,3,
                  APPLY_CHA,4,6,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_EYES,
            	0,AFF2_ULTRAVISION,0,0,
  },
{111, "pretty gold earring in the shape of a <3",
             "A &+Mv&+mer&+My pretty &+Ygold &+mea&+Mrr&+ming&n &+win the shape of a &+R<3&+w&n forged by &+W%s &+Llies here." ,
             "a &+Mv&+mer&+My pretty &+Ygold &+mea&+Mrr&+ming&n &+win the shape of a &+R<3&+w&n",
                  {SMALL_GOLD_ORE,SMALL_GOLD_ORE,0,0,0},
                  APPLY_LUCK, 8,10,
                  APPLY_CHA,8,10,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_EARRING,
            	0,0,0,0,
  },
{112, "evil looking gold skull shaped earring",
             "An &+Re&+rv&+Ri&+rl&n looking &+Ygold &+Lsk&+Yu&+Lll sh&+Yap&+Led ea&+Yrri&+Lng&+w&n forged by &+W%s &+Llies here." ,
             "an &+Re&+rv&+Ri&+rl&n looking &+Ygold &+Lsk&+Yu&+Lll sh&+Yap&+Led ea&+Yrri&+Lng&+w&n",
                  {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
                  APPLY_CON, -4,-5,
                  APPLY_INT_MAX, 2,3,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_EARRING,
            	0,0,0,0,
  },
{113, "ugly copper mask",
             "An &+yu&+Lg&+yl&+Ly &+ycopper mask forged by &+W%s &+Llies here." ,
             "an &+yu&+Lg&+yl&+Ly &+ycopper mask",
                  {SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
                  APPLY_CHA, -10,-12,
                  APPLY_STR, 5,7,
                  80,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_FACE,
            	0,0,0,0,
  },
{114, "suit of glowing mithril platemail",
  "A suit of &+Yg&+ml&+Yo&+mw&+Yi&+mn&+Yg &+mmithril p&+Ll&+ma&+Lt&+me&+Lm&+ma&+Li&+ml &+wwith &+rspikes &+walong the chest forged by &+W%s &+Llies here." ,
             "a suit of &+Yg&+ml&+Yo&+mw&+Yi&+mn&+Yg &+mmithril p&+Ll&+ma&+Lt&+me&+Lm&+ma&+Li&+ml &+wwith &+rspikes &+walong the chest",
                  {LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0},
                  APPLY_CON_MAX, 4,5,
                  APPLY_STR_MAX, 4,5,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_BODY,
            	AFF_SENSE_LIFE,0,0,0,
  },
{115, "gold necklace",
"A &+Ygold nec&+mk&+Ylace &+wwith a &+mmithril &+Yc&+mh&+Ya&+mr&+Ym &+win the shape of a &+Gd&+ga&+Gg&+gg&+Ge&+gr&+w&n forged by &+W%s &+Llies here." ,
             "a &+Ygold nec&+mk&+Ylace &+wwith a &+mmithril &+Yc&+mh&+Ya&+mr&+Ym &+win the shape of a &+Gd&+ga&+Gg&+gg&+Ge&+gr&+w&n",
                 {SMALL_MITHRIL_ORE,LARGE_GOLD_ORE,0,0,0},
                  APPLY_AGI_MAX, 2,3,
                  APPLY_DEX_MAX, 2,3,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_NECK,
            	0,0,0,0,
  },
{116, "noisy mithril chain cloak",
             "A &+Rno&+ri&+Rsy &+mmithril &+Wc&+wh&+Wa&+wi&+Wn &+ycloak&n forged by &+W%s &+Llies here." ,
             "a &+Rno&+ri&+Rsy &+mmithril &+Wc&+wh&+Wa&+wi&+Wn &+ycloak&n",
                 {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
                  APPLY_AGI, -8,-10,
                  APPLY_DEX, 2,3,
                  50,50,
                  ANTI,
                 CLASS_NONE,
                 ITEM_WEAR_ABOUT,
            	AFF_DETECT_INVISIBLE,0,0,0,
  },
{117,        "platinum quiver",
             "A large &+Wplatinum quiver &+wwith inlaid &+Ygold &+wand &+mmithril &+wdesigns&n forged by &+W%s &+Llies here." ,
             "a large &+Wplatinum quiver &+wwith inlaid &+Ygold &+wand &+mmithril &+wdesigns",
             {MEDIUM_MITHRIL_ORE,LARGE_GOLD_ORE,0,0,0},
             APPLY_HITROLL, 1,2,
             APPLY_DAMROLL, 0,1,
             50,50,
             ANTI,
             CLASS_NONE,
             ITEM_WEAR_QUIVER,
             AFF_PROT_FIRE,0,0,0,
  },
{118,"mithril shield",
"A nearly &+rin&+Rvi&+rnc&+Rib&+rle &+mmithril sh&+Lie&+mld&n with &+Rma&+Ls&+Rsi&+Lv&+Re &+Rsharp s&+rp&+Ri&+rk&+Re&+rs&+w forged by &+W%s &+Llies here." ,
            "a nearly &+rin&+Rvi&+rnc&+Rib&+rle &+mmithril sh&+Lie&+mld&n with &+Rma&+Ls&+Rsi&+Lv&+Re &+Rsharp s&+rp&+Ri&+rk&+Re&+rs&+w",
            {MEDIUM_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0,0},
            APPLY_DEX, -6,-8,
            APPLY_DAMROLL, 2,3,
            50,50,
            ANTI,
            CLASS_NONE,
            ITEM_WEAR_SHIELD,
            0,AFF2_PROT_ACID,0,0,
  },
{119,       "platinum and gold bracelet",
            "A &+Wplatinum &+wand &+Ygold b&+Wr&+Ya&+Wc&+Ye&+Wl&+Ye&+Wt &+win the shape of a &+Gsn&+ga&+Gke&+w&n forged by &+W%s &+Llies here." ,
            "a &+Wplatinum &+wand &+Ygold b&+Wr&+Ya&+Wc&+Ye&+Wl&+Ye&+Wt &+win the shape of a &+Gsn&+ga&+Gke&+w&n",
            {MEDIUM_GOLD_ORE,MEDIUM_PLATINUM_ORE,0,0,0},
            APPLY_AGI, 6,8,
            APPLY_AGI_MAX, 2,3,
            50,50,
            ANTI,
            CLASS_NONE,
            ITEM_WEAR_WRIST,
            0,0,0,0,
  },
{120,       "cloudy mask",
            "A &+bclo&+Bud&+cy&n &+Lm&+was&+Lk with &+yetc&+Lhin&+ygs&n forged by &+W%s &+Llies here." ,
             "a &+bclo&+Bud&+cy&n &+Lm&+was&+Lk with &+yetc&+Lhin&+ygs&n",
             {MEDIUM_SILVER_ORE,LARGE_SILVER_ORE,MEDIUM_COPPER_ORE,0,0},
             APPLY_AGI, 8,10,
             APPLY_STR, 8,10,
             50,50,
             ANTI,
             CLASS_NONE,
             ITEM_WEAR_FACE,
             AFF_PROT_FIRE,0,0,0,
  },
{121,       "jagged pair of gold horns",
            "A &+yjagged&n &+Lpair of &+Ygold&n &+Rh&+ror&+Rns&n forged by &+W%s &+Llies here." ,
             "a &+yjagged&n &+Lpair of &+Ygold&n &+Rh&+ror&+Rns&n",
             {MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0,0},
             APPLY_DAMROLL, 2,3,
             APPLY_SAVING_SPELL, -1,-2,
             50,50,
             ANTI,
             CLASS_NONE,
             ITEM_WEAR_HORN,
             AFF_SENSE_LIFE,0,0,0,
  },
{122,       "smooth pair of silver horns",
            "A &+gsm&+Goo&+gth&n &+ypair of&n &+wsilver&n &+Lh&+worn&+Ls&n forged by &+W%s &+Llies here." ,
             "a &+gsm&+Goo&+gth&n &+ypair of&n &+wsilver&n &+Lh&+worn&+Ls&n",
             {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
             APPLY_CON_MAX, 2,3,
             APPLY_SAVING_SPELL, -1,2,
             50,50,
             ANTI,
             CLASS_NONE,
             ITEM_WEAR_HORN,
             AFF_SENSE_LIFE,0,0,0,
  },
 {123,       "sack lined in silver",
             "A &+Llight&+Wweight&n &+Csack&n lined in &+Lsilver&n forged by &+W%s &+Llies here." ,
             "a &+Llight&+Wweight&n &+Csack&n lined in &+Lsilver&n",
              {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
              APPLY_MOVE, 12,15,
              APPLY_STR, 6,8,
              50,50,
              ANTI,
              CLASS_NONE,
              ITEM_WEAR_BACK,
              0,0,0,0,
  },
  {124,       "band of silver lined with mithril",
              "A &+Lp&+wolish&+Led band of &+wsilver&n lined with &+mmithril&n forged by &+W%s &+Llies here." ,
              "a &+Lp&+wolish&+Led band of &+wsilver&n lined with &+mmithril&n",
              {MEDIUM_SILVER_ORE,SMALL_MITHRIL_ORE,0,0,0},
              APPLY_MOVE, 26,30,
              APPLY_STR, 8,10,
              50,50,
              ANTI,
              CLASS_NONE,
              ITEM_WEAR_FINGER,
              AFF_PROT_FIRE,0,0,0,
  },
  {125,       "silver ring",
                "A thin &+wsilver&n &+Br&+bin&+bg&n with a &+Wplatinum&n &+Rh&+rea&+Rrt&n forged by &+W%s &+Llies here." ,
                "a thin &+wsilver&n &+Br&+bin&+bg&n with a &+Wplatinum&n &+Rh&+rea&+Rrt&n",
                {SMALL_SILVER_ORE,SMALL_PLATINUM_ORE,0,0,0},
                APPLY_HIT, 12,15,
                APPLY_STR, 8,10,
                50,50,
                ANTI,
                CLASS_NONE,
                ITEM_WEAR_FINGER,
                0,0,0,0,
  },
  {126,       "copper ball",
                  "A &+ycopper&n &+Gb&+ga&+Gll&n with a &+Wdangling&n &+Ygolden&n &+Ys&+Wt&+Ya&+Wr&n forged by &+W%s &+Llies here." ,
                  "a &+ycopper&n &+Gb&+ga&+Gll&n with a &+Wdangling&n &+Ygolden&n &+Ys&+Wt&+Ya&+Wr&n",
                  {SMALL_COPPER_ORE,SMALL_GOLD_ORE,0,0,0},
                  APPLY_HIT, 10,12,
                  APPLY_AGI, 4,5,
                  50,50,
                  ANTI,
                  CLASS_NONE,
                  ITEM_WEAR_EARRING,
                  0,0,0,0,
  },
  {127,       "sterling silver snake chain",
                "A &+Cste&+crl&+Cing &nsilver &+Gs&+gnak&+Ge&n &+Lch&na&+Lin&n forged by &+W%s &+Llies here." ,
                "a &+Cste&+crl&+Cing &nsilver &+Gs&+gnak&+Ge&n &+Lch&na&+Lin&n",
                {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,0},
                APPLY_CON, 6,7,
                APPLY_SAVING_SPELL, -1,-2,
                50,50,
                ANTI,
                CLASS_NONE,
                ITEM_WEAR_NECK,
                0,AFF2_PROT_GAS,0,0,
    },
  {128,       "sterling silver chain",
                "A &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with &+Rtr&+rip&+Rle he&+rart&+Rs&n forged by &+W%s &+Llies here." ,
                "a &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with &+Rtr&+rip&+Rle he&+rart&+Rs&n",
                {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,0},
                APPLY_HIT, 11,12,
                APPLY_CHA, 8,10,
                50,50,
                ANTI,
                CLASS_NONE,
                ITEM_WEAR_NECK,
                0,0,0,0,
  },
  {129,       "sterling silver chain",
                "A &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with &+ciron&n &+cst&+Carfi&+csh&n forged by &+W%s &+Llies here." ,
                "a &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with &+ciron&n &+cst&+Carfi&+csh&n",
                {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_IRON_ORE,0},
                  APPLY_HIT, 11,12,
                  APPLY_SAVING_PARA, -1,-2,
                  50,50,
                  ANTI,
                  CLASS_NONE,
                  ITEM_WEAR_NECK,
                  0,0,0,0,
  },
  {130,       "sterling silver chain",
                  "A &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with a &+mmithril&n &+Cb&ni&+Cb&nl&+Ce&n forged by &+W%s &+Llies here." ,
                  "A &+Cste&+crl&+Cing &nsilver &+Lch&na&+Lin&n with a &+mmithril&n &+Cb&ni&+Cb&nl&+Ce&n",
                  {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_MITHRIL_ORE,0},
                    APPLY_WIS_MAX, 2,3,
                    APPLY_SAVING_BREATH, -1,-2,
                    50,50,
                    ANTI,
                    CLASS_NONE,
                    ITEM_WEAR_NECK,
                    0,0,AFF3_SPIRIT_WARD,0,
  },
  {131,       "magical silver charm",
                    "A &+Cma&+cgi&+Ccal&n silver &+Cc&nh&+Ca&nr&+Cm&n of the &+Mwild&+mmage&n forged by &+W%s &+Llies here." ,
                    "a &+Cma&+cgi&+Ccal&n silver &+Cc&nh&+Ca&nr&+Cm&n of the &+Mwild&+mmage&n",
                    {SMALL_SILVER_ORE,SMALL_SILVER_ORE,MEDIUM_SILVER_ORE,SMALL_MITHRIL_ORE,0},
                     APPLY_INT_MAX, 0,2,
                     APPLY_SAVING_PARA, -1,-2,
                     50,50,
                     ANTI,
                     CLASS_NONE,
                     ITEM_WEAR_WRIST,
                     0,AFF2_DETECT_MAGIC,0,0,
  },
  {132,       "magical copper charm",
                      "A &+Cma&+cgi&+Ccal&n &+ycopper&n &+Cc&nh&+Ca&nr&+Cm&n with &+Linscr&+wipti&+Lons&n forged by &+W%s &+Llies here." ,
                      "a &+Cma&+cgi&+Ccal&n &+ycopper&n &+Cc&nh&+Ca&nr&+Cm&n with &+Linscr&+wipti&+Lons&n",
                     {SMALL_COPPER_ORE,SMALL_COPPER_ORE,SMALL_COPPER_ORE,LARGE_COPPER_ORE,0},
                      APPLY_HIT, 10,12,
                      APPLY_SAVING_SPELL, -1,-2,
                      50,50,
                      ANTI,
                      CLASS_NONE,
                      ITEM_WEAR_WRIST,
                      0,AFF2_DETECT_MAGIC,0,0,
  },
};
